version: '3.7'

services:
  app:
    build: .
    ports:
      - '8080:3001'
      - '80:5173'
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/shopper
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopper
    volumes:
      - ./back/postgres:/var/lib/postgresql/data
